# Generated by Django 5.2.7 on 2025-10-31 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_bnbuser_is_email_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="bnbuser",
            name="registered_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="registered at",
            ),
            preserve_default=False,
        ),
    ]
