# Generated by Django 5.2.7 on 2025-11-04 15:35

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_remove_colorschemechoices_icon_and_more'),
        ('users', '0003_bnbuser_registered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Phone Number')),
                ('listing_urls', models.JSONField(default=list)),
                ('domain_name', models.URLField(blank=True, null=True)),
                ('color_scheme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='builder.colorschemechoices')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='builder.themechoices')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('lead_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.leadregistration')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.package')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.promotion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
