# Generated by Django 5.2.7 on 2025-11-04 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0004_remove_colorschemechoices_icon_and_more"),
        ("users", "0004_leadregistration_registrationoptions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leadregistration",
            options={
                "verbose_name": "Lead Registration",
                "verbose_name_plural": "Lead Registrations",
            },
        ),
        migrations.AlterModelOptions(
            name="registrationoptions",
            options={
                "verbose_name": "Registration Option",
                "verbose_name_plural": "Registration Options",
            },
        ),
        migrations.AlterField(
            model_name="leadregistration",
            name="color_scheme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="builder.colorschemechoices",
            ),
        ),
        migrations.AlterField(
            model_name="leadregistration",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="leadregistration",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="leadregistration",
            name="listing_urls",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="leadregistration",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="builder.themechoices",
            ),
        ),
        migrations.AlterField(
            model_name="registrationoptions",
            name="lead_registration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration_options",
                to="users.leadregistration",
            ),
        ),
        migrations.AlterField(
            model_name="registrationoptions",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="builder.package",
            ),
        ),
        migrations.AlterField(
            model_name="registrationoptions",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="builder.promotion",
            ),
        ),
    ]
