# Generated by Django 5.2.7 on 2025-11-05 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_leadregistration_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationoptions",
            name="lead_registration",
        ),
        migrations.RemoveField(
            model_name="registrationoptions",
            name="package",
        ),
        migrations.RemoveField(
            model_name="registrationoptions",
            name="promotion",
        ),
        migrations.DeleteModel(
            name="LeadRegistration",
        ),
        migrations.DeleteModel(
            name="RegistrationOptions",
        ),
    ]
