import daisyui from 'daisyui';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/templates/**/*.html',
    './src/static/src/**/*.{js,ts,jsx,tsx}',
    './src/apps/**/templates/**/*.html',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter var', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [
    daisyui,
  ],
  daisyui: {
    themes: [
      {
        framer: {
          'primary': '#6366F1',
          'primary-content': '#FFFFFF',
          'secondary': '#06B6D4',
          'secondary-content': '#FFFFFF',
          'accent': '#A855F7',
          'accent-content': '#FFFFFF',
          'neutral': '#242424',
          'neutral-content': '#FFFFFF',
          'base-100': '#0A0A0A',
          'base-200': '#131313',
          'base-300': '#1A1A1A',
          'base-content': '#FFFFFF',
          'info': '#3B82F6',
          'info-content': '#FFFFFF',
          'success': '#10B981',
          'success-content': '#FFFFFF',
          'warning': '#F59E0B',
          'warning-content': '#000000',
          'error': '#EF4444',
          'error-content': '#FFFFFF',
          '--rounded-box': '1rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '1.9rem',
          '--animation-btn': '0.2s',
          '--animation-input': '0.2s',
          '--btn-focus-scale': '0.98',
        },
        light: {
          'primary': '#6366F1',
          'primary-content': '#FFFFFF',
          'secondary': '#06B6D4',
          'secondary-content': '#FFFFFF',
          'accent': '#A855F7',
          'accent-content': '#FFFFFF',
          'neutral': '#DEE2E6',
          'neutral-content': '#0A0A0A',
          'base-100': '#FFFFFF',
          'base-200': '#F8F9FA',
          'base-300': '#E9ECEF',
          'base-content': '#0A0A0A',
          'info': '#3B82F6',
          'info-content': '#FFFFFF',
          'success': '#10B981',
          'success-content': '#FFFFFF',
          'warning': '#F59E0B',
          'warning-content': '#000000',
          'error': '#EF4444',
          'error-content': '#FFFFFF',
          '--rounded-box': '1rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '1.9rem',
          '--animation-btn': '0.2s',
          '--animation-input': '0.2s',
          '--btn-focus-scale': '0.98',
        },
      },
    ],
    darkTheme: 'framer',
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
}