# Generated by Django 5.2.7 on 2025-11-06 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name_plural": "properties"},
        ),
    ]
