# Generated by Django 5.2.7 on 2025-11-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_image_image_property_lead_alter_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': 'Amenities'},
        ),
    ]
