# Generated by Django 5.2.7 on 2025-11-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_amenity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(help_text='Article content in Markdown or HTML')),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of tags, e.g., ['beach', 'family', 'adventure']")),
                ('read_time', models.IntegerField(default=5, help_text='Estimated read time in minutes')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='properties.property')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='TouristAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('distance', models.CharField(help_text="e.g., '2 km away', '10 min walk'", max_length=100)),
                ('category', models.CharField(help_text="e.g., 'Restaurant', 'Museum', 'Beach', 'Park'", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/')),
                ('image_url', models.URLField(blank=True, help_text='Fallback if image not uploaded', null=True)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order, lower numbers first')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='properties.property')),
            ],
            options={
                'verbose_name': 'Tourist Attraction',
                'verbose_name_plural': 'Tourist Attractions',
                'ordering': ['order', 'distance'],
            },
        ),
    ]
