# Generated by Django 5.2.7 on 2025-11-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0018_remove_website_airbnb_listing_url_and_more'),
        ('properties', '0005_article_touristattraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('platform', models.CharField(choices=[('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('expedia', 'Expedia'), ('tripadvisor', 'Tripadvisor')], default='airbnb', max_length=255)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='properties.property')),
                ('website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='builder.website')),
            ],
            options={
                'verbose_name_plural': 'Listings',
            },
        ),
    ]
