from django.core.management.base import BaseCommand
from apps.builder.models import ColorSchemeChoices

PREDEFINED_COLOR_SCHEMES = [
    # ── Light themes ─────────────────────────────────────────────────────
    {
        "name": "Light",
        "internal_name": "light",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(49.96% 0.151 255.59)"},
            {"name": "secondary", "value": "oklch(62.81% 0.149 275.75)"},
            {"name": "accent",    "value": "oklch(74.68% 0.184 199.82)"},
            {"name": "neutral",   "value": "oklch(24.57% 0.014 266.37)"},
            {"name": "base",      "value": "oklch(100% 0 0)"},
            {"name": "info",      "value": "oklch(84.25% 0.149 230.69)"},
            {"name": "success",   "value": "oklch(84.25% 0.149 140.69)"},
            {"name": "warning",   "value": "oklch(84.25% 0.149 80.69)"},
            {"name": "error",     "value": "oklch(84.25% 0.149 20.69)"},
        ],
    },
    {
        "name": "Dark",
        "internal_name": "dark",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(65.99% 0.151 255.59)"},
            {"name": "secondary", "value": "oklch(74.68% 0.149 275.75)"},
            {"name": "accent",    "value": "oklch(84.25% 0.184 199.82)"},
            {"name": "neutral",   "value": "oklch(24.57% 0.014 266.37)"},
            {"name": "base",      "value": "oklch(18% 0 0)"},
            {"name": "info",      "value": "oklch(84.25% 0.149 230.69)"},
            {"name": "success",   "value": "oklch(84.25% 0.149 140.69)"},
            {"name": "warning",   "value": "oklch(84.25% 0.149 80.69)"},
            {"name": "error",     "value": "oklch(84.25% 0.149 20.69)"},
        ],
    },
    {
        "name": "Cupcake",
        "internal_name": "cupcake",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(69.59% 0.151 255.59)"},
            {"name": "secondary", "value": "oklch(74.68% 0.149 275.75)"},
            {"name": "accent",    "value": "oklch(84.25% 0.184 199.82)"},
            {"name": "neutral",   "value": "oklch(24.57% 0.014 266.37)"},
            {"name": "base",      "value": "oklch(98% 0.02 60)"},
            {"name": "info",      "value": "oklch(84.25% 0.149 230.69)"},
            {"name": "success",   "value": "oklch(84.25% 0.149 140.69)"},
            {"name": "warning",   "value": "oklch(84.25% 0.149 80.69)"},
            {"name": "error",     "value": "oklch(84.25% 0.149 20.69)"},
        ],
    },
    {
        "name": "Bumblebee",
        "internal_name": "bumblebee",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(89.12% 0.151 90)"},
            {"name": "secondary", "value": "oklch(20% 0.02 240)"},
            {"name": "accent",    "value": "oklch(84.25% 0.184 199.82)"},
            {"name": "neutral",   "value": "oklch(24.57% 0.014 266.37)"},
            {"name": "base",      "value": "oklch(98% 0.02 60)"},
            {"name": "info",      "value": "oklch(84.25% 0.149 230.69)"},
            {"name": "success",   "value": "oklch(84.25% 0.149 140.69)"},
            {"name": "warning",   "value": "oklch(84.25% 0.149 80.69)"},
            {"name": "error",     "value": "oklch(84.25% 0.149 20.69)"},
        ],
    },
    {
        "name": "Emerald",
        "internal_name": "emerald",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(62% 0.135 158)"},
            {"name": "secondary", "value": "oklch(74% 0.12 170)"},
            {"name": "accent",    "value": "oklch(84% 0.15 190)"},
            {"name": "neutral",   "value": "oklch(24% 0.02 260)"},
            {"name": "base",      "value": "oklch(98% 0.02 60)"},
            {"name": "info",      "value": "oklch(84% 0.15 230)"},
            {"name": "success",   "value": "oklch(84% 0.15 140)"},
            {"name": "warning",   "value": "oklch(84% 0.15 80)"},
            {"name": "error",     "value": "oklch(84% 0.15 20)"},
        ],
    },
    {
        "name": "Corporate",
        "internal_name": "corporate",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(65% 0.12 260)"},
            {"name": "secondary", "value": "oklch(70% 0.1 240)"},
            {"name": "accent",    "value": "oklch(75% 0.15 280)"},
            {"name": "neutral",   "value": "oklch(30% 0.02 260)"},
            {"name": "base",      "value": "oklch(98% 0 0)"},
            {"name": "info",      "value": "oklch(80% 0.15 220)"},
            {"name": "success",   "value": "oklch(80% 0.15 140)"},
            {"name": "warning",   "value": "oklch(80% 0.15 80)"},
            {"name": "error",     "value": "oklch(80% 0.15 20)"},
        ],
    },
    {
        "name": "Synthwave",
        "internal_name": "synthwave",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(65% 0.25 300)"},
            {"name": "secondary", "value": "oklch(70% 0.22 330)"},
            {"name": "accent",    "value": "oklch(75% 0.2 280)"},
            {"name": "neutral",   "value": "oklch(25% 0.03 260)"},
            {"name": "base",      "value": "oklch(15% 0.02 280)"},
            {"name": "info",      "value": "oklch(75% 0.2 220)"},
            {"name": "success",   "value": "oklch(75% 0.2 140)"},
            {"name": "warning",   "value": "oklch(75% 0.2 80)"},
            {"name": "error",     "value": "oklch(75% 0.2 20)"},
        ],
    },
    {
        "name": "Retro",
        "internal_name": "retro",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(70% 0.15 30)"},
            {"name": "secondary", "value": "oklch(75% 0.12 60)"},
            {"name": "accent",    "value": "oklch(80% 0.18 90)"},
            {"name": "neutral",   "value": "oklch(30% 0.02 260)"},
            {"name": "base",      "value": "oklch(97% 0.02 60)"},
            {"name": "info",      "value": "oklch(80% 0.15 220)"},
            {"name": "success",   "value": "oklch(80% 0.15 140)"},
            {"name": "warning",   "value": "oklch(80% 0.15 80)"},
            {"name": "error",     "value": "oklch(80% 0.15 20)"},
        ],
    },
    {
        "name": "Cyberpunk",
        "internal_name": "cyberpunk",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(75% 0.25 320)"},
            {"name": "secondary", "value": "oklch(80% 0.22 280)"},
            {"name": "accent",    "value": "oklch(85% 0.2 240)"},
            {"name": "neutral",   "value": "oklch(20% 0.02 260)"},
            {"name": "base",      "value": "oklch(10% 0 0)"},
            {"name": "info",      "value": "oklch(80% 0.2 220)"},
            {"name": "success",   "value": "oklch(80% 0.2 140)"},
            {"name": "warning",   "value": "oklch(80% 0.2 80)"},
            {"name": "error",     "value": "oklch(80% 0.2 20)"},
        ],
    },
    {
        "name": "Valentine",
        "internal_name": "valentine",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(70% 0.2 340)"},
            {"name": "secondary", "value": "oklch(75% 0.18 10)"},
            {"name": "accent",    "value": "oklch(80% 0.16 300)"},
            {"name": "neutral",   "value": "oklch(30% 0.02 260)"},
            {"name": "base",      "value": "oklch(98% 0.02 60)"},
            {"name": "info",      "value": "oklch(80% 0.15 220)"},
            {"name": "success",   "value": "oklch(80% 0.15 140)"},
            {"name": "warning",   "value": "oklch(80% 0.15 80)"},
            {"name": "error",     "value": "oklch(80% 0.15 20)"},
        ],
    },
    {
        "name": "Halloween",
        "internal_name": "halloween",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(60% 0.25 30)"},
            {"name": "secondary", "value": "oklch(45% 0.2 280)"},
            {"name": "accent",    "value": "oklch(75% 0.25 70)"},
            {"name": "neutral",   "value": "oklch(20% 0.02 260)"},
            {"name": "base",      "value": "oklch(10% 0 0)"},
            {"name": "info",      "value": "oklch(75% 0.2 220)"},
            {"name": "success",   "value": "oklch(75% 0.2 140)"},
            {"name": "warning",   "value": "oklch(75% 0.2 80)"},
            {"name": "error",     "value": "oklch(75% 0.2 20)"},
        ],
    },
    {
        "name": "Garden",
        "internal_name": "garden",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(65% 0.15 150)"},
            {"name": "secondary", "value": "oklch(70% 0.12 170)"},
            {"name": "accent",    "value": "oklch(75% 0.18 200)"},
            {"name": "neutral",   "value": "oklch(30% 0.02 260)"},
            {"name": "base",      "value": "oklch(98% 0.02 60)"},
            {"name": "info",      "value": "oklch(80% 0.15 220)"},
            {"name": "success",   "value": "oklch(80% 0.15 140)"},
            {"name": "warning",   "value": "oklch(80% 0.15 80)"},
            {"name": "error",     "value": "oklch(80% 0.15 20)"},
        ],
    },
    {
        "name": "Forest",
        "internal_name": "forest",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(55% 0.18 140)"},
            {"name": "secondary", "value": "oklch(60% 0.15 150)"},
            {"name": "accent",    "value": "oklch(65% 0.12 160)"},
            {"name": "neutral",   "value": "oklch(25% 0.02 260)"},
            {"name": "base",      "value": "oklch(15% 0 0)"},
            {"name": "info",      "value": "oklch(75% 0.15 220)"},
            {"name": "success",   "value": "oklch(75% 0.15 140)"},
            {"name": "warning",   "value": "oklch(75% 0.15 80)"},
            {"name": "error",     "value": "oklch(75% 0.15 20)"},
        ],
    },
    {
        "name": "Aqua",
        "internal_name": "aqua",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(65% 0.2 200)"},
            {"name": "secondary", "value": "oklch(70% 0.18 220)"},
            {"name": "accent",    "value": "oklch(75% 0.16 240)"},
            {"name": "neutral",   "value": "oklch(30% 0.02 260)"},
            {"name": "base",      "value": "oklch(98% 0.02 60)"},
            {"name": "info",      "value": "oklch(80% 0.15 220)"},
            {"name": "success",   "value": "oklch(80% 0.15 140)"},
            {"name": "warning",   "value": "oklch(80% 0.15 80)"},
            {"name": "error",     "value": "oklch(80% 0.15 20)"},
        ],
    },
    {
        "name": "Lofi",
        "internal_name": "lofi",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(60% 0.1 260)"},
            {"name": "secondary", "value": "oklch(65% 0.08 280)"},
            {"name": "accent",    "value": "oklch(70% 0.12 300)"},
            {"name": "neutral",   "value": "oklch(30% 0.02 260)"},
            {"name": "base",      "value": "oklch(98% 0.02 60)"},
            {"name": "info",      "value": "oklch(75% 0.1 220)"},
            {"name": "success",   "value": "oklch(75% 0.1 140)"},
            {"name": "warning",   "value": "oklch(75% 0.1 80)"},
            {"name": "error",     "value": "oklch(75% 0.1 20)"},
        ],
    },
    {
        "name": "Pastel",
        "internal_name": "pastel",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(80% 0.1 260)"},
            {"name": "secondary", "value": "oklch(82% 0.08 280)"},
            {"name": "accent",    "value": "oklch(84% 0.12 300)"},
            {"name": "neutral",   "value": "oklch(90% 0.02 260)"},
            {"name": "base",      "value": "oklch(99% 0.01 60)"},
            {"name": "info",      "value": "oklch(85% 0.08 220)"},
            {"name": "success",   "value": "oklch(85% 0.08 140)"},
            {"name": "warning",   "value": "oklch(85% 0.08 80)"},
            {"name": "error",     "value": "oklch(85% 0.08 20)"},
        ],
    },
    {
        "name": "Fantasy",
        "internal_name": "fantasy",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(60% 0.2 290)"},
            {"name": "secondary", "value": "oklch(65% 0.18 320)"},
            {"name": "accent",    "value": "oklch(70% 0.16 340)"},
            {"name": "neutral",   "value": "oklch(25% 0.02 260)"},
            {"name": "base",      "value": "oklch(15% 0 0)"},
            {"name": "info",      "value": "oklch(75% 0.15 220)"},
            {"name": "success",   "value": "oklch(75% 0.15 140)"},
            {"name": "warning",   "value": "oklch(75% 0.15 80)"},
            {"name": "error",     "value": "oklch(75% 0.15 20)"},
        ],
    },
    {
        "name": "Wireframe",
        "internal_name": "wireframe",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(0% 0 0)"},
            {"name": "secondary", "value": "oklch(0% 0 0)"},
            {"name": "accent",    "value": "oklch(0% 0 0)"},
            {"name": "neutral",   "value": "oklch(0% 0 0)"},
            {"name": "base",      "value": "oklch(100% 0 0)"},
            {"name": "info",      "value": "oklch(0% 0 0)"},
            {"name": "success",   "value": "oklch(0% 0 0)"},
            {"name": "warning",   "value": "oklch(0% 0 0)"},
            {"name": "error",     "value": "oklch(0% 0 0)"},
        ],
    },
    {
        "name": "Black",
        "internal_name": "black",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(80% 0.15 260)"},
            {"name": "secondary", "value": "oklch(80% 0.15 260)"},
            {"name": "accent",    "value": "oklch(80% 0.15 260)"},
            {"name": "neutral",   "value": "oklch(15% 0 0)"},
            {"name": "base",      "value": "oklch(0% 0 0)"},
            {"name": "info",      "value": "oklch(80% 0.15 220)"},
            {"name": "success",   "value": "oklch(80% 0.15 140)"},
            {"name": "warning",   "value": "oklch(80% 0.15 80)"},
            {"name": "error",     "value": "oklch(80% 0.15 20)"},
        ],
    },
    {
        "name": "Luxury",
        "internal_name": "luxury",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(30% 0.05 260)"},
            {"name": "secondary", "value": "oklch(25% 0.04 280)"},
            {"name": "accent",    "value": "oklch(20% 0.03 300)"},
            {"name": "neutral",   "value": "oklch(15% 0.02 260)"},
            {"name": "base",      "value": "oklch(5% 0 0)"},
            {"name": "info",      "value": "oklch(70% 0.15 220)"},
            {"name": "success",   "value": "oklch(70% 0.15 140)"},
            {"name": "warning",   "value": "oklch(70% 0.15 80)"},
            {"name": "error",     "value": "oklch(70% 0.15 20)"},
        ],
    },
    {
        "name": "Dracula",
        "internal_name": "dracula",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(70% 0.25 330)"},
            {"name": "secondary", "value": "oklch(65% 0.22 290)"},
            {"name": "accent",    "value": "oklch(75% 0.2 170)"},
            {"name": "neutral",   "value": "oklch(25% 0.02 260)"},
            {"name": "base",      "value": "oklch(15% 0 0)"},
            {"name": "info",      "value": "oklch(75% 0.2 220)"},
            {"name": "success",   "value": "oklch(75% 0.2 140)"},
            {"name": "warning",   "value": "oklch(75% 0.2 80)"},
            {"name": "error",     "value": "oklch(75% 0.2 20)"},
        ],
    },
    {
        "name": "CMYK",
        "internal_name": "cmyk",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(65% 0.25 260)"},
            {"name": "secondary", "value": "oklch(70% 0.25 300)"},
            {"name": "accent",    "value": "oklch(75% 0.25 200)"},
            {"name": "neutral",   "value": "oklch(20% 0 0)"},
            {"name": "base",      "value": "oklch(98% 0 0)"},
            {"name": "info",      "value": "oklch(75% 0.25 220)"},
            {"name": "success",   "value": "oklch(75% 0.25 140)"},
            {"name": "warning",   "value": "oklch(75% 0.25 80)"},
            {"name": "error",     "value": "oklch(75% 0.25 20)"},
        ],
    },
    {
        "name": "Autumn",
        "internal_name": "autumn",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(55% 0.18 30)"},
            {"name": "secondary", "value": "oklch(60% 0.15 50)"},
            {"name": "accent",    "value": "oklch(65% 0.12 70)"},
            {"name": "neutral",   "value": "oklch(30% 0.02 260)"},
            {"name": "base",      "value": "oklch(95% 0.02 60)"},
            {"name": "info",      "value": "oklch(75% 0.15 220)"},
            {"name": "success",   "value": "oklch(75% 0.15 140)"},
            {"name": "warning",   "value": "oklch(75% 0.15 80)"},
            {"name": "error",     "value": "oklch(75% 0.15 20)"},
        ],
    },
    {
        "name": "Business",
        "internal_name": "business",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(60% 0.12 260)"},
            {"name": "secondary", "value": "oklch(65% 0.1 240)"},
            {"name": "accent",    "value": "oklch(70% 0.15 280)"},
            {"name": "neutral",   "value": "oklch(25% 0.02 260)"},
            {"name": "base",      "value": "oklch(98% 0 0)"},
            {"name": "info",      "value": "oklch(75% 0.15 220)"},
            {"name": "success",   "value": "oklch(75% 0.15 140)"},
            {"name": "warning",   "value": "oklch(75% 0.15 80)"},
            {"name": "error",     "value": "oklch(75% 0.15 20)"},
        ],
    },
    {
        "name": "Acid",
        "internal_name": "acid",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(75% 0.25 90)"},
            {"name": "secondary", "value": "oklch(80% 0.22 120)"},
            {"name": "accent",    "value": "oklch(85% 0.2 150)"},
            {"name": "neutral",   "value": "oklch(20% 0.02 260)"},
            {"name": "base",      "value": "oklch(98% 0.02 60)"},
            {"name": "info",      "value": "oklch(80% 0.2 220)"},
            {"name": "success",   "value": "oklch(80% 0.2 140)"},
            {"name": "warning",   "value": "oklch(80% 0.2 80)"},
            {"name": "error",     "value": "oklch(80% 0.2 20)"},
        ],
    },
    {
        "name": "Lemonade",
        "internal_name": "lemonade",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(75% 0.2 90)"},
            {"name": "secondary", "value": "oklch(80% 0.18 110)"},
            {"name": "accent",    "value": "oklch(85% 0.16 130)"},
            {"name": "neutral",   "value": "oklch(30% 0.02 260)"},
            {"name": "base",      "value": "oklch(98% 0.02 60)"},
            {"name": "info",      "value": "oklch(80% 0.15 220)"},
            {"name": "success",   "value": "oklch(80% 0.15 140)"},
            {"name": "warning",   "value": "oklch(80% 0.15 80)"},
            {"name": "error",     "value": "oklch(80% 0.15 20)"},
        ],
    },
    {
        "name": "Night",
        "internal_name": "night",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(65% 0.15 260)"},
            {"name": "secondary", "value": "oklch(70% 0.12 240)"},
            {"name": "accent",    "value": "oklch(75% 0.18 280)"},
            {"name": "neutral",   "value": "oklch(20% 0.02 260)"},
            {"name": "base",      "value": "oklch(12% 0 0)"},
            {"name": "info",      "value": "oklch(75% 0.15 220)"},
            {"name": "success",   "value": "oklch(75% 0.15 140)"},
            {"name": "warning",   "value": "oklch(75% 0.15 80)"},
            {"name": "error",     "value": "oklch(75% 0.15 20)"},
        ],
    },
    {
        "name": "Coffee",
        "internal_name": "coffee",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(55% 0.1 40)"},
            {"name": "secondary", "value": "oklch(60% 0.08 50)"},
            {"name": "accent",    "value": "oklch(65% 0.12 60)"},
            {"name": "neutral",   "value": "oklch(25% 0.02 260)"},
            {"name": "base",      "value": "oklch(15% 0 0)"},
            {"name": "info",      "value": "oklch(70% 0.1 220)"},
            {"name": "success",   "value": "oklch(70% 0.1 140)"},
            {"name": "warning",   "value": "oklch(70% 0.1 80)"},
            {"name": "error",     "value": "oklch(70% 0.1 20)"},
        ],
    },
    {
        "name": "Winter",
        "internal_name": "winter",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(65% 0.15 220)"},
            {"name": "secondary", "value": "oklch(70% 0.12 240)"},
            {"name": "accent",    "value": "oklch(75% 0.18 260)"},
            {"name": "neutral",   "value": "oklch(30% 0.02 260)"},
            {"name": "base",      "value": "oklch(98% 0.02 220)"},
            {"name": "info",      "value": "oklch(80% 0.15 220)"},
            {"name": "success",   "value": "oklch(80% 0.15 140)"},
            {"name": "warning",   "value": "oklch(80% 0.15 80)"},
            {"name": "error",     "value": "oklch(80% 0.15 20)"},
        ],
    },
    {
        "name": "Nord",
        "internal_name": "nord",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(55% 0.12 230)"},
            {"name": "secondary", "value": "oklch(60% 0.1 240)"},
            {"name": "accent",    "value": "oklch(65% 0.15 260)"},
            {"name": "neutral",   "value": "oklch(25% 0.02 260)"},
            {"name": "base",      "value": "oklch(95% 0.02 220)"},
            {"name": "info",      "value": "oklch(70% 0.12 220)"},
            {"name": "success",   "value": "oklch(70% 0.12 140)"},
            {"name": "warning",   "value": "oklch(70% 0.12 80)"},
            {"name": "error",     "value": "oklch(70% 0.12 20)"},
        ],
    },

    # ── Catppuccin (Latte, Frappé, Macchiato, Mocha) ─────────────────────
    {
        "name": "Catppuccin Latte",
        "internal_name": "latte",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(50.13% 0.152 258.49)"},
            {"name": "secondary", "value": "oklch(59.69% 0.131 277.15)"},
            {"name": "accent",    "value": "oklch(49.36% 0.183 199.82)"},
            {"name": "neutral",   "value": "oklch(88.14% 0.014 266.37)"},
            {"name": "base",      "value": "oklch(98.71% 0.007 266.37)"},
            {"name": "info",      "value": "oklch(74.68% 0.149 230.69)"},
            {"name": "success",   "value": "oklch(74.68% 0.149 140.69)"},
            {"name": "warning",   "value": "oklch(74.68% 0.149 80.69)"},
            {"name": "error",     "value": "oklch(74.68% 0.149 20.69)"},
        ],
    },
    {
        "name": "Catppuccin Frappé",
        "internal_name": "frappe",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(65.99% 0.151 255.59)"},
            {"name": "secondary", "value": "oklch(74.68% 0.149 275.75)"},
            {"name": "accent",    "value": "oklch(84.25% 0.184 199.82)"},
            {"name": "neutral",   "value": "oklch(34.57% 0.014 266.37)"},
            {"name": "base",      "value": "oklch(26% 0.02 260)"},
            {"name": "info",      "value": "oklch(84.25% 0.149 230.69)"},
            {"name": "success",   "value": "oklch(84.25% 0.149 140.69)"},
            {"name": "warning",   "value": "oklch(84.25% 0.149 80.69)"},
            {"name": "error",     "value": "oklch(84.25% 0.149 20.69)"},
        ],
    },
    {
        "name": "Catppuccin Macchiato",
        "internal_name": "macchiato",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(65.99% 0.151 255.59)"},
            {"name": "secondary", "value": "oklch(74.68% 0.149 275.75)"},
            {"name": "accent",    "value": "oklch(84.25% 0.184 199.82)"},
            {"name": "neutral",   "value": "oklch(29.57% 0.014 266.37)"},
            {"name": "base",      "value": "oklch(20% 0.02 260)"},
            {"name": "info",      "value": "oklch(84.25% 0.149 230.69)"},
            {"name": "success",   "value": "oklch(84.25% 0.149 140.69)"},
            {"name": "warning",   "value": "oklch(84.25% 0.149 80.69)"},
            {"name": "error",     "value": "oklch(84.25% 0.149 20.69)"},
        ],
    },
    {
        "name": "Catppuccin Mocha",
        "internal_name": "mocha",
        "theme_colors": [
            {"name": "primary",   "value": "oklch(65.99% 0.151 255.59)"},
            {"name": "secondary", "value": "oklch(74.68% 0.149 275.75)"},
            {"name": "accent",    "value": "oklch(84.25% 0.184 199.82)"},
            {"name": "neutral",   "value": "oklch(24.57% 0.014 266.37)"},
            {"name": "base",      "value": "oklch(15% 0 0)"},
            {"name": "info",      "value": "oklch(84.25% 0.149 230.69)"},
            {"name": "success",   "value": "oklch(84.25% 0.149 140.69)"},
            {"name": "warning",   "value": "oklch(84.25% 0.149 80.69)"},
            {"name": "error",     "value": "oklch(84.25% 0.149 20.69)"},
        ],
    },
]


class Command(BaseCommand):
    help = "Imports predefined color schemes into the database"

    def handle(self, *args, **options):
        for scheme_data in PREDEFINED_COLOR_SCHEMES:
            scheme_name = scheme_data["name"]
            if ColorSchemeChoices.objects.filter(name=scheme_name).exists():
                self.stdout.write(
                    self.style.WARNING(
                        f'Color scheme "{scheme_name}" already exists. Skipping.'
                    )
                )
                continue

            ColorSchemeChoices.objects.create(**scheme_data)
            self.stdout.write(
                self.style.SUCCESS(
                    f'Successfully imported color scheme "{scheme_name}".'
                )
            )
