# Generated by Django 5.2.7 on 2025-11-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="colorschemechoices",
            name="icon",
            field=models.CharField(default="DEFAULT-ICON", max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="themechoices",
            name="icon_name",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name="themechoices",
            name="preview_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
