# Generated by Django 5.2.7 on 2025-11-03 08:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_colorschemechoices_icon_themechoices_icon_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.PositiveSmallIntegerField(choices=[(1, 'One time payment'), (2, 'Monthly'), (3, 'Quarterly'), (4, 'Yearly'), (5, 'Every 2 years'), (6, 'Every 3 years'), (7, 'Every 5 years')], default=1)),
                ('label', models.CharField(choices=[('Builder', 'Builder'), ('Hosting', 'Hosting'), ('Add-on', 'Add-on')], default='Builder', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='website',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('discount_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('units_available', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('promotion_code', models.CharField(blank=True, max_length=30, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='builder.package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebsitePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='builder.package')),
                ('promotion_applied', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='builder.promotion')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='builder.website')),
            ],
            options={
                'verbose_name': 'Website Plan Package',
                'verbose_name_plural': 'Website Plan Packages',
                'unique_together': {('website', 'package')},
            },
        ),
    ]
