# Generated by Django 5.2.7 on 2025-11-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0003_package_website_owner_promotion_websiteplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colorschemechoices",
            name="icon",
        ),
        migrations.AddField(
            model_name="colorschemechoices",
            name="internal_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="colorschemechoices",
            name="theme_colors",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="colorschemechoices",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
