# Generated by Django 5.2.7 on 2025-11-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0005_leadregistration_registrationoptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadregistration",
            name="email",
            field=models.EmailField(max_length=255, verbose_name="Email"),
        ),
    ]
