# Generated by Django 5.2.7 on 2025-11-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0006_alter_leadregistration_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="extra_info",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="leadregistration",
            name="domain_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
