# Generated by Django 5.2.7 on 2025-11-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0008_package_currency_alter_package_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadregistration",
            name="extra_requirements",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
