# Generated by Django 5.2.7 on 2025-11-07 13:09

import django.db.models.deletion
from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0009_leadregistration_extra_requirements"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationoptions",
            name="lead_registration",
        ),
        migrations.RemoveField(
            model_name="registrationoptions",
            name="package",
        ),
        migrations.RemoveField(
            model_name="registrationoptions",
            name="promotion",
        ),
        migrations.DeleteModel(
            name="LeadRegistration",
        ),
        migrations.DeleteModel(
            name="RegistrationOptions",
        ),
        migrations.CreateModel(
            name="LeadRegistration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update time"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                ("listing_urls", models.JSONField(blank=True, default=list)),
                (
                    "domain_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("extra_requirements", models.JSONField(blank=True, default=dict)),
                (
                    "color_scheme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="builder.colorschemechoices",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="builder.themechoices",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Registration",
                "verbose_name_plural": "Lead Registrations",
            },
        ),
        migrations.CreateModel(
            name="RegistrationOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update time"),
                ),
                (
                    "lead_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_options",
                        to="builder.leadregistration",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.package",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="builder.promotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registration Option",
                "verbose_name_plural": "Registration Options",
            },
        ),
    ]
