# Generated by Django 5.2.7 on 2025-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0011_leadregistration_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadregistration",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
