# Generated by Django 5.2.7 on 2025-11-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0012_leadregistration_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationoptions",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registrationoptions",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
