# Generated by Django 5.2.7 on 2025-11-09 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0013_registrationoptions_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookPayload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('lead_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.leadregistration')),
            ],
            options={
                'verbose_name': 'Stripe Webhook Payload',
            },
        ),
    ]
