# Generated by Django 5.2.7 on 2025-11-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_stripewebhookpayload'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripewebhookpayload',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
