# Generated by Django 5.2.7 on 2025-11-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_stripewebhookpayload_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripewebhookpayload',
            name='processed_successfully',
            field=models.BooleanField(default=False),
        ),
    ]
