# Generated by Django 5.2.7 on 2025-11-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0016_stripewebhookpayload_processed_successfully'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripewebhookpayload',
            options={'ordering': ['updated_at'], 'verbose_name': 'Stripe Webhook Payload'},
        ),
        migrations.AddField(
            model_name='leadregistration',
            name='checkout_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
