# Generated by Django 5.2.7 on 2025-11-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0017_alter_stripewebhookpayload_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='airbnb_listing_url',
        ),
        migrations.RemoveField(
            model_name='website',
            name='booking_listing_url',
        ),
    ]
